# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.18.4
parchment_minecraft_version=1.20.1
parchment_mappings_version=2023.09.03
# Mod Properties
mod_version=0.8.2-forge1.5.3+mc1.20.1
maven_group=cn.sh1rocu
archives_base_name=touhoulittlemaid-fabric
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.92.6+1.20.1
jei_version=15.20.0.112-fabric
architectury_api_version=9.2.14+fabric
rei_version=12.1.785
emi_version=1.1.22+1.20.1+fabric
cloth_config_version=11.1.136
jade_version=11.13.1+fabric
iron_chests_version=2.0.2
carry_on_version=2.1.2.7-fabric
patchouli_version=1.20.1-84.1-fabric
accessories_version=1.0.0-beta.47+1.20.1